### ISSUE TITLE
Preferences questionnaire on front-end

### ISSUE THREAD

**Issue by anmolpuri96** [nyu-software-engineering/robot-stock-trader#1]
Set up the front-end interface for the trading software

**Comment by bloombar** [comment]
Hi @nyu-software-engineering/robot-stock-trader team - your task board needs a bit of cleanup - user stories in the Sprint 0 taskboard should all have the 'user story' and '1 - sprint backlog' labels.  Tasks should all have the 'task' label, but not the '1 - sprint backlog' label.  Tasks should have a label that corresponds with which column they are in on the task board.  Check out labeling guidelines on the web site and see me with questions.
